-- MySQL Script generated by MySQL Workbench
-- 11/23/17 17:46:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parqueo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parqueo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parqueo` DEFAULT CHARACTER SET utf8 ;
USE `parqueo` ;

-- -----------------------------------------------------
-- Table `parqueo`.`TipoVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`TipoVehiculo` (
  `idTipoVehiculo` INT NOT NULL AUTO_INCREMENT,
  `TipoVehic` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`Vehiculo` (
  `placaVehiculo` VARCHAR(6) NOT NULL,
  `TipoVehiculo_idTipoVehiculo` INT NOT NULL,
  PRIMARY KEY (`placaVehiculo`),
  INDEX `fk_Vehiculo_TipoVehiculo_idx` (`TipoVehiculo_idTipoVehiculo` ASC),
  CONSTRAINT `fk_Vehiculo_TipoVehiculo`
    FOREIGN KEY (`TipoVehiculo_idTipoVehiculo`)
    REFERENCES `parqueo`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`TipoLugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`TipoLugar` (
  `idTipoLugar` INT NOT NULL AUTO_INCREMENT,
  `TipoLuga` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTipoLugar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`LugarParqueo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`LugarParqueo` (
  `idLugarParqueo` INT NOT NULL AUTO_INCREMENT,
  `idTipoLugar` INT NOT NULL,
  `disponibilidad` TINYINT(1) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`idLugarParqueo`),
  INDEX `fk_LugarParqueo_TipoLugar1_idx` (`idTipoLugar` ASC),
  CONSTRAINT `fk_LugarParqueo_TipoLugar1`
    FOREIGN KEY (`idTipoLugar`)
    REFERENCES `parqueo`.`TipoLugar` (`idTipoLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`RegistroParqueo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`RegistroParqueo` (
  `idRegistroParqueo` INT NOT NULL AUTO_INCREMENT,
  `fechaHoraEntrada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `placaVehiculo` VARCHAR(6) NOT NULL,
  `LugarParqueo_idLugarParqueo` INT NOT NULL,
  `estadoRegistro` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idRegistroParqueo`, `placaVehiculo`, `LugarParqueo_idLugarParqueo`),
  INDEX `fk_Vehiculo_has_LugarParqueo_Vehiculo1_idx` (`placaVehiculo` ASC),
  INDEX `fk_RegistroParqueo_LugarParqueo1_idx` (`LugarParqueo_idLugarParqueo` ASC),
  CONSTRAINT `fk_Vehiculo_has_LugarParqueo_Vehiculo1`
    FOREIGN KEY (`placaVehiculo`)
    REFERENCES `parqueo`.`Vehiculo` (`placaVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroParqueo_LugarParqueo1`
    FOREIGN KEY (`LugarParqueo_idLugarParqueo`)
    REFERENCES `parqueo`.`LugarParqueo` (`idLugarParqueo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `FechaFactura` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fechaSalida` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idRegistroParqueo` INT NOT NULL,
  `placaVehiculo` VARCHAR(6) NOT NULL,
  `idLugarParqueo` INT NOT NULL,
  `valParqueo` DOUBLE NOT NULL,
  PRIMARY KEY (`idFactura`, `idRegistroParqueo`, `placaVehiculo`, `idLugarParqueo`),
  INDEX `fk_Factura_RegistroParqueo1_idx` (`idRegistroParqueo` ASC, `placaVehiculo` ASC, `idLugarParqueo` ASC),
  CONSTRAINT `fk_Factura_RegistroParqueo1`
    FOREIGN KEY (`idRegistroParqueo` , `placaVehiculo` , `idLugarParqueo`)
    REFERENCES `parqueo`.`RegistroParqueo` (`idRegistroParqueo` , `placaVehiculo` , `LugarParqueo_idLugarParqueo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`Tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`Tarifa` (
  `idTarifa` INT NOT NULL AUTO_INCREMENT,
  `nombreTarifa` VARCHAR(45) NOT NULL,
  `precioFraccion` DOUBLE NOT NULL,
  `TipoVehiculo_idTipoVehiculo` INT NOT NULL,
  PRIMARY KEY (`idTarifa`, `TipoVehiculo_idTipoVehiculo`),
  INDEX `fk_Tarifa_TipoVehiculo1_idx` (`TipoVehiculo_idTipoVehiculo` ASC),
  CONSTRAINT `fk_Tarifa_TipoVehiculo1`
    FOREIGN KEY (`TipoVehiculo_idTipoVehiculo`)
    REFERENCES `parqueo`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueo`.`Parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`Parqueadero` (
  `nitParqueadero` INT NOT NULL,
  `nomParqueadero` VARCHAR(45) NOT NULL,
  `numLugares` INT NOT NULL,
  PRIMARY KEY (`nitParqueadero`))
ENGINE = InnoDB;

USE `parqueo` ;

-- -----------------------------------------------------
-- Placeholder table for view `parqueo`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueo`.`detalle` (`idFactura` INT, `idRegistroParqueo` INT, `FechaFactura` INT, `fechaHoraEntrada` INT, `fechaSalida` INT, `duracion` INT, `HORAS` INT, `MINUTOS` INT, `placaVehiculo` INT, `TipoVehic` INT, `idLugarParqueo` INT, `valParqueo` INT);

-- -----------------------------------------------------
-- View `parqueo`.`detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parqueo`.`detalle`;
USE `parqueo`;
CREATE  OR REPLACE VIEW detalle AS
    SELECT 
        f.idFactura,
        f.idRegistroParqueo,
        f.FechaFactura,
        rp.fechaHoraEntrada,
        f.fechaSalida,
        (SELECT TIMEDIFF(f.FechaFactura, rp.fechaHoraEntrada)) AS duracion,
        (SELECT HOUR(TIMEDIFF(f.FechaFactura, rp.fechaHoraEntrada))) AS HORAS,
        (SELECT MINUTE(TIMEDIFF(f.FechaFactura, rp.fechaHoraEntrada))) AS MINUTOS,
        f.placaVehiculo,
        tv.TipoVehic,
        f.idLugarParqueo,
        f.valParqueo
    FROM
        factura AS f
            INNER JOIN
        registroparqueo AS rp ON f.idRegistroParqueo = rp.idRegistroParqueo
            INNER JOIN
        vehiculo AS v ON rp.placaVehiculo = v.placaVehiculo
            INNER JOIN
        tipoVehiculo AS tv ON v.TipoVehiculo_idTipoVehiculo = tv.idTipoVehiculo;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
